# Generated by Django 4.2.2 on 2023-08-02 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('text', models.TextField(default='Нет описания', verbose_name='текст новости')),
                ('created_at', models.DateTimeField(verbose_name='дата создания новости')),
                ('updated_at', models.DateTimeField(verbose_name='дата изменеия новости')),
                ('views_count', models.IntegerField(default=0, verbose_name='число просмотров')),
                ('author', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_new_object', to=settings.AUTH_USER_MODEL)),
                ('likes_users', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='лайки')),
            ],
        ),
    ]
