# Generated by Django 4.2.2 on 2023-08-02 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlenew',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата изменеия новости'),
        ),
    ]
