# Generated by Django 4.2.2 on 2023-09-07 03:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0002_alter_articlenew_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlenew',
            name='likes_users',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL, verbose_name='лайки'),
        ),
    ]
